// src/react/Counter.tsx
import React from "react";
import { ReactHost } from "./ReactHost";
import { CounterService } from "src/app/services/counter.service";
import { useNgInject, useNgSignal } from "@rectangular/react";

const Counter: React.FC = () => {
  const counterService = useNgInject(CounterService);
  const [count, setCount] = useNgSignal(counterService.count);

  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  return (
    <ReactHost>
      <div>
        <div>Counter: {count}</div>
        <div>
          <button onClick={decrement}>-</button>
          <button onClick={increment}>+</button>
          <button>empty</button>
        </div>
      </div>
    </ReactHost>
  );
};

export default Counter;

// src/app/ng-counter/ng-counter.component.ts
import { Component, inject } from '@angular/core';
import { CounterService } from '../services/counter.service';
import { NgHostComponent } from "../ng-host/ng-host.component";

@Component({
  selector: 'ng-counter',
  standalone: true,
  imports: [NgHostComponent],
  templateUrl: './ng-counter.component.html',
  styleUrl: './ng-counter.component.css'
})
export class NgCounterComponent {
  private counterService = inject(CounterService);

  increment() {
    this.counterService.increment();
  }

  decrement() {
    this.counterService.decrement();
  }

  get count() {
    return this.counterService.getCount();
  }
}

<ng-host>
  Counter: {{ count() }}

  <br />
  <button (click)="decrement()">-</button>
  <button (click)="increment()">+</button>
</ng-host>
